[package]
name = "screeps-game-api"
version = "0.8.0"
authors = ["David Ross <daboross@daboross.net>"]
documentation = "https://docs.rs/screeps-game-api/"
edition = "2018"
include = [
    "Cargo.toml",
    "Web.toml",
    "src/**/*",
    "javascript/**/*",
    "tests/**/*",
    "examples/**/*",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/rustyscreeps/screeps-game-api/"
description = "WASM bindings to the in-game Screeps API"

[lib]
name = "screeps"

[badges]
travis-ci = { repository = "rustyscreeps/screeps-game-api" }

[dependencies]
arrayvec = "0.4"
enum-iterator = "0.3"
log = "0.4"
num-derive = "0.2"
num-traits = "0.2"
parse-display = "0.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_repr = "0.1"
stdweb = "0.4"
stdweb-derive = "0.5"

[features]
check-all-casts = []

# Disable Game.market interfaces - used in season 1
disable-market = []

# Disable terminal structures - proposed but not used in season 1
disable-terminal = []

# Enable score structures and resource - used in season 1
enable-score = []

# Seasonal server, season 1; market removed, score structures and resource added
seasonal-season-1 = ["disable-market", "enable-score"]
