default_deploy_mode = "upload"

[upload]
username = "your username or email"
password = "your password"
branch = "default"
# ptr = false
# hostname = "screeps.com"
# ssl = true
# port = 443

# [copy]
# destination = "your copy destination"
# prune = false

# [build]
# use absolute file path to get out of "target/"
# ouptut_js_file = "main.js"
# output_wasm_file = "compiled.wasm"
