[package]
name = "screeps-game-api"
version = "0.5.0"
edition = "2018"
authors = ["David Ross <daboross@daboross.net>"]
documentation = "https://docs.rs/screeps-game-api/"
include = [
    "Cargo.toml",
    "Web.toml",
    "src/**/*",
    "javascript/**/*",
    "tests/**/*",
    "examples/**/*",
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/daboross/screeps-in-rust-via-wasm/"
description = "WASM bindings to the in-game Screeps API"

[lib]
name = "screeps"

[dependencies]
enum-iterator = "0.3"
log = "0.4"
num-derive = "0.2"
num-traits = "0.2"
parse-display = "0.1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_repr = "0.1"
scoped-tls = "0.1"
stdweb = "0.4"
stdweb-derive = "0.5"

[features]
check-all-casts = []
